### PR TITLE
feat: add multi-stage docker image build template

### PR DESCRIPTION
**Pull request by denisvmedia**

### CODE REVIEW

**Comment by linuxbandit** [comment]
thank you for the PR! can you double-check the commented lines? I am not sure the example usage is correct (e.g.: the stage name of the `extends`)

**Comment by denisvmedia** [comment]
Updated. Anything else? ;)

**Comment by denisvmedia** [comment]
@linuxbandit can we merge it?

**Comment by linuxbandit** [comment]
can you change the target branch to `feat/docker-multistage-build-cache` ? we just pushed it for you

**Comment by linuxbandit** [comment]
nvm forgot we could do it

**Pull request merged**
